### ISSUE TITLE
Eliminate C compiler dependency on nightly

### ISSUE THREAD

**Issue by roblabla** [gimli-rs/unwind-rs#3]
Currently, a C compiler is necessary for the trampoline function. Maybe this dependency could be eliminated on nightly, through the use of the `asm` and `naked_functions` nightly features ? (Or maybe the `global_asm` feature ? Both seem like they could work).

**Comment by main--** [comment]
You are correct. The only reason I did it this way was to avoid requiring nightly rust. If that's a problem for you, feel free to change it or just do things differently for the aarch64 version.
