### ISSUE TITLE
Is this MIT OR Apache-2.0 dual-licensed?

### ISSUE THREAD

**Issue by bjorn3** [gimli-rs/unwind-rs#38]
`Cargo.toml` doesn't have a `license` field.

cc @philipc, @main--, @jrmuizel and @roblabla (all authors excluding myself)

**Comment by roblabla** [comment]
Ah, I always sort of expected this project was MIT/Apache-2.0, since other crates in the gimli org (like gimli and addr2line) are.

**Comment by bjorn3** [comment]
So did I. I searched for it just in case, as I wanted to copy code to another project.

I agree to allow my contributions to the unwind-rs project to be distributed under the terms of the "MIT OR Apache-2.0" license.

@roblabla Is my assumption based on your response that you too allow your contributions to be distributed under this license correct?

**Comment by jrmuizel** [comment]
I agree to allow my contributions to the unwind-rs project to be distributed under the terms of the "MIT OR Apache-2.0" license.

**Comment by roblabla** [comment]
Yes, of course!

I agree to allow my contributions to the unwind-rs project to be distributed under the terms of the "MIT OR Apache-2.0" license.

**Comment by philipc** [comment]
I agree to allow my contributions to the unwind-rs project to be distributed under the terms of the "MIT OR Apache-2.0" license.

**Comment by bjorn3** [comment]
Ping @main--

**Comment by main--** [comment]
Sorry, totally missed this!

I agree to allow my contributions to the unwind-rs project to be distributed under the terms of the "MIT OR Apache-2.0" license.

**Comment by bjorn3** [comment]
Ok, thanks! I will open a PR to add the licenses.
